services:
  - type: web
    name: telegram-app-monitor
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: CHAT_ID
        sync: false
    autoDeploy: true