services:
  - type: web
    name: App-Update-Bot
    env: python
    # פקודת ההתקנה נשארת זהה
    buildCommand: "pip install -r requirements.txt"
    # פקודת ההרצה משתנה כדי להפעיל את הסקריפט המשולב שלנו
    startCommand: "python app.py"
    # אומרים ל-Render באיזו כתובת לבדוק אם השירות חי
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.6
